package com.tsumiki;

import java.lang.reflect.Method;

public class PythonTests {

    static void RunPythonTests(){
        try {
            for(int i = 1; i <= 100; i++){
                Method m = PythonTests.class.getDeclaredMethod("PythonTest" + i);
                m.invoke(new PythonTests());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /*
     * Warning:
     * This class consists ENTIRELY of tests generated by Python code.
     * No human wrote this code.
     * By continuing to read further you understand this
     * And by continuing to scroll down you understand that, even if your IDE is yelling about
     * all of these functions not being called
     * YOU WILL IGNORE THEM.
     *
     * If it really bugs you that much,
     * And you really want to remove the IDE "errors" saying these functions are not being called,
     * Either change your IDE settings,
     * or make a program that generates code and calls these functions one by one.
     */

    private static void PythonTest1(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("pryse".toCharArray(), new byte[]{0,0,0,1,1});
        assert wordle.getAnswers().size() == 1086;

        wordle.ApplyGuess("coure".toCharArray(), new byte[]{0,2,0,0,1});
        assert wordle.getAnswers().size() == 99;

        wordle.ApplyGuess("mokes".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 54;

        wordle.ApplyGuess("hones".toCharArray(), new byte[]{0,2,1,2,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("noxes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("noses".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest2(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("nates".toCharArray(), new byte[]{0,0,0,2,0});
        assert wordle.getAnswers().size() == 601;

        wordle.ApplyGuess("horsy".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 140;

        wordle.ApplyGuess("duddy".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 75;

        wordle.ApplyGuess("bever".toCharArray(), new byte[]{0,0,0,2,2});
        assert wordle.getAnswers().size() == 26;

        wordle.ApplyGuess("wrier".toCharArray(), new byte[]{0,0,1,2,2});
        assert wordle.getAnswers().size() == 14;

        wordle.ApplyGuess("piler".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("miler".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest3(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("harms".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 1768;

        wordle.ApplyGuess("queys".toCharArray(), new byte[]{0,1,1,0,0});
        assert wordle.getAnswers().size() == 85;

        wordle.ApplyGuess("unite".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 25;

        wordle.ApplyGuess("pouke".toCharArray(), new byte[]{1,2,2,0,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("coupe".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest4(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("davit".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 854;

        wordle.ApplyGuess("scalp".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 246;

        wordle.ApplyGuess("peace".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 120;

        wordle.ApplyGuess("muter".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("foots".toCharArray(), new byte[]{1,2,0,1,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest5(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("train".toCharArray(), new byte[]{0,0,2,0,0});
        assert wordle.getAnswers().size() == 420;

        wordle.ApplyGuess("kudzu".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 251;

        wordle.ApplyGuess("gadis".toCharArray(), new byte[]{0,1,0,0,1});
        assert wordle.getAnswers().size() == 66;

        wordle.ApplyGuess("scalp".toCharArray(), new byte[]{2,1,2,0,1});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("spacy".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest6(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("hoody".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 714;

        wordle.ApplyGuess("chyle".toCharArray(), new byte[]{2,0,1,0,0});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("carny".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("carvy".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("carby".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest7(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("paste".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 981;

        wordle.ApplyGuess("datal".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 243;

        wordle.ApplyGuess("baccy".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("cured".toCharArray(), new byte[]{2,0,0,2,1});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("coden".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest8(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("homes".toCharArray(), new byte[]{2,0,0,1,2});
        assert wordle.getAnswers().size() == 26;

        wordle.ApplyGuess("hests".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 17;

        wordle.ApplyGuess("heaps".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 12;

        wordle.ApplyGuess("herls".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest9(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("tubby".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 5818;

        wordle.ApplyGuess("dalis".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 114;

        wordle.ApplyGuess("artel".toCharArray(), new byte[]{0,0,0,1,1});
        assert wordle.getAnswers().size() == 32;

        wordle.ApplyGuess("chelp".toCharArray(), new byte[]{1,1,1,1,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest10(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("alcid".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2537;

        wordle.ApplyGuess("golps".toCharArray(), new byte[]{0,0,0,1,2});
        assert wordle.getAnswers().size() == 52;

        wordle.ApplyGuess("perts".toCharArray(), new byte[]{1,1,0,0,2});
        assert wordle.getAnswers().size() == 10;

        wordle.ApplyGuess("epees".toCharArray(), new byte[]{0,1,0,2,2});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("jupes".toCharArray(), new byte[]{0,0,2,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("kypes".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("hypes".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest11(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("bores".toCharArray(), new byte[]{0,0,0,1,2});
        assert wordle.getAnswers().size() == 419;

        wordle.ApplyGuess("jibed".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 283;

        wordle.ApplyGuess("tulsi".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 12;

        wordle.ApplyGuess("nexus".toCharArray(), new byte[]{1,2,0,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("genus".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("venus".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest12(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("mooed".toCharArray(), new byte[]{0,0,2,0,0});
        assert wordle.getAnswers().size() == 368;

        wordle.ApplyGuess("sooks".toCharArray(), new byte[]{1,0,2,0,0});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("ghost".toCharArray(), new byte[]{2,0,2,2,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest13(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("gutsy".toCharArray(), new byte[]{1,0,1,0,0});
        assert wordle.getAnswers().size() == 60;

        wordle.ApplyGuess("tiger".toCharArray(), new byte[]{2,0,2,1,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest14(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("razer".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 555;

        wordle.ApplyGuess("humor".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 344;

        wordle.ApplyGuess("edema".toCharArray(), new byte[]{1,1,0,0,1});
        assert wordle.getAnswers().size() == 43;

        wordle.ApplyGuess("degas".toCharArray(), new byte[]{2,2,0,2,0});
        assert wordle.getAnswers().size() == 11;

        wordle.ApplyGuess("dewan".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest15(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("imams".toCharArray(), new byte[]{0,0,2,0,1});
        assert wordle.getAnswers().size() == 199;

        wordle.ApplyGuess("skill".toCharArray(), new byte[]{2,0,0,2,0});
        assert wordle.getAnswers().size() == 14;

        wordle.ApplyGuess("scale".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("scala".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("scaly".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("scalp".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest16(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("divos".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 1106;

        wordle.ApplyGuess("etats".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 259;

        wordle.ApplyGuess("monas".toCharArray(), new byte[]{2,2,1,0,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest17(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("human".toCharArray(), new byte[]{0,2,0,2,0});
        assert wordle.getAnswers().size() == 61;

        wordle.ApplyGuess("jurat".toCharArray(), new byte[]{0,2,0,2,0});
        assert wordle.getAnswers().size() == 27;

        wordle.ApplyGuess("pulas".toCharArray(), new byte[]{0,2,1,2,0});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("fugal".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("ducal".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest18(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("flava".toCharArray(), new byte[]{0,2,2,0,0});
        assert wordle.getAnswers().size() == 117;

        wordle.ApplyGuess("droit".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 64;

        wordle.ApplyGuess("claps".toCharArray(), new byte[]{0,2,2,0,1});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("slake".toCharArray(), new byte[]{1,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest19(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("leves".toCharArray(), new byte[]{0,0,0,2,2});
        assert wordle.getAnswers().size() == 450;

        wordle.ApplyGuess("brood".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 61;

        wordle.ApplyGuess("pones".toCharArray(), new byte[]{0,1,0,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("oxies".toCharArray(), new byte[]{2,0,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest20(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("downa".toCharArray(), new byte[]{0,0,1,0,1});
        assert wordle.getAnswers().size() == 169;

        wordle.ApplyGuess("ooped".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 100;

        wordle.ApplyGuess("thaws".toCharArray(), new byte[]{0,0,1,1,2});
        assert wordle.getAnswers().size() == 19;

        wordle.ApplyGuess("walls".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 14;

        wordle.ApplyGuess("wakfs".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("waurs".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest21(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("tacho".toCharArray(), new byte[]{2,0,0,0,0});
        assert wordle.getAnswers().size() == 239;

        wordle.ApplyGuess("kiths".toCharArray(), new byte[]{0,0,1,0,2});
        assert wordle.getAnswers().size() == 54;

        wordle.ApplyGuess("turms".toCharArray(), new byte[]{2,0,2,0,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("tyres".toCharArray(), new byte[]{2,0,2,1,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("terts".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("terfs".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest22(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("hexed".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 5121;

        wordle.ApplyGuess("neigh".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2264;

        wordle.ApplyGuess("diene".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2264;

        wordle.ApplyGuess("aired".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 187;

        wordle.ApplyGuess("grope".toCharArray(), new byte[]{0,1,2,0,0});
        assert wordle.getAnswers().size() == 27;

        wordle.ApplyGuess("rooms".toCharArray(), new byte[]{1,0,2,0,0});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("flour".toCharArray(), new byte[]{2,2,2,0,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest23(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("trock".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 355;

        wordle.ApplyGuess("evict".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 122;

        wordle.ApplyGuess("pacta".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 54;

        wordle.ApplyGuess("brens".toCharArray(), new byte[]{2,2,1,0,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("brule".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest24(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("datal".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 3237;

        wordle.ApplyGuess("whims".toCharArray(), new byte[]{0,1,0,0,2});
        assert wordle.getAnswers().size() == 71;

        wordle.ApplyGuess("hyens".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("ouphs".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("rukhs".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("vughs".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest25(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("merks".toCharArray(), new byte[]{0,0,2,0,2});
        assert wordle.getAnswers().size() == 198;

        wordle.ApplyGuess("caged".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 41;

        wordle.ApplyGuess("tarts".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 32;

        wordle.ApplyGuess("laris".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("saris".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("naris".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("zaris".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest26(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("ludes".toCharArray(), new byte[]{1,1,0,1,0});
        assert wordle.getAnswers().size() == 37;

        wordle.ApplyGuess("uncle".toCharArray(), new byte[]{1,0,0,2,2});
        assert wordle.getAnswers().size() == 9;

        wordle.ApplyGuess("foule".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest27(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("pleas".toCharArray(), new byte[]{0,1,1,1,0});
        assert wordle.getAnswers().size() == 150;

        wordle.ApplyGuess("ankle".toCharArray(), new byte[]{1,0,0,1,1});
        assert wordle.getAnswers().size() == 60;

        wordle.ApplyGuess("melba".toCharArray(), new byte[]{0,1,1,0,1});
        assert wordle.getAnswers().size() == 26;

        wordle.ApplyGuess("lacet".toCharArray(), new byte[]{2,2,0,2,1});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("lated".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("later".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest28(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("mucky".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 886;

        wordle.ApplyGuess("gutsy".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 239;

        wordle.ApplyGuess("creds".toCharArray(), new byte[]{2,0,0,0,2});
        assert wordle.getAnswers().size() == 56;

        wordle.ApplyGuess("chops".toCharArray(), new byte[]{2,0,2,0,2});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("clows".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest29(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("pards".toCharArray(), new byte[]{2,1,0,0,0});
        assert wordle.getAnswers().size() == 79;

        wordle.ApplyGuess("pelta".toCharArray(), new byte[]{2,2,0,0,1});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("peaky".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest30(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("linac".toCharArray(), new byte[]{2,2,2,0,0});
        assert wordle.getAnswers().size() == 20;

        wordle.ApplyGuess("liner".toCharArray(), new byte[]{2,2,2,0,0});
        assert wordle.getAnswers().size() == 15;

        wordle.ApplyGuess("linux".toCharArray(), new byte[]{2,2,2,0,0});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("lints".toCharArray(), new byte[]{2,2,2,0,0});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("linin".toCharArray(), new byte[]{2,2,2,0,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest31(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("gleds".toCharArray(), new byte[]{2,0,0,0,0});
        assert wordle.getAnswers().size() == 142;

        wordle.ApplyGuess("chime".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 9;

        wordle.ApplyGuess("gamba".toCharArray(), new byte[]{2,2,2,0,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest32(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("poaka".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 1971;

        wordle.ApplyGuess("stime".toCharArray(), new byte[]{0,0,1,1,0});
        assert wordle.getAnswers().size() == 36;

        wordle.ApplyGuess("magic".toCharArray(), new byte[]{1,1,0,1,0});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("limax".toCharArray(), new byte[]{0,1,1,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("ihram".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest33(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("troop".toCharArray(), new byte[]{1,1,0,0,0});
        assert wordle.getAnswers().size() == 248;

        wordle.ApplyGuess("yetts".toCharArray(), new byte[]{0,2,0,2,0});
        assert wordle.getAnswers().size() == 11;

        wordle.ApplyGuess("berth".toCharArray(), new byte[]{0,2,2,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("nertz".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest34(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("fetta".toCharArray(), new byte[]{0,1,0,0,1});
        assert wordle.getAnswers().size() == 990;

        wordle.ApplyGuess("moory".toCharArray(), new byte[]{0,0,2,0,0});
        assert wordle.getAnswers().size() == 18;

        wordle.ApplyGuess("abode".toCharArray(), new byte[]{2,0,2,0,2});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("alone".toCharArray(), new byte[]{2,0,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("axone".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest35(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("trogs".toCharArray(), new byte[]{0,1,1,0,0});
        assert wordle.getAnswers().size() == 332;

        wordle.ApplyGuess("zupas".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("doura".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest36(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("feist".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 1350;

        wordle.ApplyGuess("golps".toCharArray(), new byte[]{1,0,1,0,0});
        assert wordle.getAnswers().size() == 15;

        wordle.ApplyGuess("bugle".toCharArray(), new byte[]{0,0,2,1,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest37(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("rupee".toCharArray(), new byte[]{0,2,0,2,0});
        assert wordle.getAnswers().size() == 90;

        wordle.ApplyGuess("luxed".toCharArray(), new byte[]{0,2,0,2,1});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("duvet".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest38(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("toted".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 595;

        wordle.ApplyGuess("toise".toCharArray(), new byte[]{1,0,1,1,0});
        assert wordle.getAnswers().size() == 62;

        wordle.ApplyGuess("busti".toCharArray(), new byte[]{0,0,1,2,1});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("sixty".toCharArray(), new byte[]{1,2,0,2,0});
        assert wordle.getAnswers().size() == 18;

        wordle.ApplyGuess("mints".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 12;

        wordle.ApplyGuess("jilts".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("lilts".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("hilts".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("wilts".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("gilts".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest39(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("jacks".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2840;

        wordle.ApplyGuess("ephod".toCharArray(), new byte[]{1,0,1,0,2});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("heyed".toCharArray(), new byte[]{1,1,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest40(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("favas".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 103;

        wordle.ApplyGuess("skegs".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest41(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("suave".toCharArray(), new byte[]{0,0,2,2,2});
        assert wordle.getAnswers().size() == 16;

        wordle.ApplyGuess("drave".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest42(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("fugue".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 557;

        wordle.ApplyGuess("cools".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 33;

        wordle.ApplyGuess("bingo".toCharArray(), new byte[]{0,0,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("tango".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest43(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("rugae".toCharArray(), new byte[]{2,0,0,0,1});
        assert wordle.getAnswers().size() == 170;

        wordle.ApplyGuess("tiyns".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 23;

        wordle.ApplyGuess("reels".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("repps".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("redos".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest44(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("knave".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2382;

        wordle.ApplyGuess("yenta".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 1188;

        wordle.ApplyGuess("groat".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 255;

        wordle.ApplyGuess("vigor".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 50;

        wordle.ApplyGuess("bolix".toCharArray(), new byte[]{0,2,2,2,0});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("folio".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest45(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("sedum".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 1487;

        wordle.ApplyGuess("scale".toCharArray(), new byte[]{1,0,1,0,0});
        assert wordle.getAnswers().size() == 389;

        wordle.ApplyGuess("foxie".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 189;

        wordle.ApplyGuess("booms".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 124;

        wordle.ApplyGuess("pruta".toCharArray(), new byte[]{0,1,0,0,1});
        assert wordle.getAnswers().size() == 23;

        wordle.ApplyGuess("narks".toCharArray(), new byte[]{1,2,1,0,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("rangs".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest46(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("fault".toCharArray(), new byte[]{2,0,0,0,0});
        assert wordle.getAnswers().size() == 154;

        wordle.ApplyGuess("yagis".toCharArray(), new byte[]{0,0,0,1,2});
        assert wordle.getAnswers().size() == 25;

        wordle.ApplyGuess("finks".toCharArray(), new byte[]{2,1,0,0,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("fries".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest47(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("plews".toCharArray(), new byte[]{0,1,1,0,0});
        assert wordle.getAnswers().size() == 513;

        wordle.ApplyGuess("virtu".toCharArray(), new byte[]{1,1,0,0,0});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("kevil".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest48(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("kokra".toCharArray(), new byte[]{0,0,0,1,1});
        assert wordle.getAnswers().size() == 911;

        wordle.ApplyGuess("mesal".toCharArray(), new byte[]{0,0,1,1,0});
        assert wordle.getAnswers().size() == 136;

        wordle.ApplyGuess("thong".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 57;

        wordle.ApplyGuess("wraps".toCharArray(), new byte[]{0,1,1,0,2});
        assert wordle.getAnswers().size() == 20;

        wordle.ApplyGuess("daris".toCharArray(), new byte[]{1,2,2,0,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("sards".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("yards".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("bards".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("cards".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest49(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("study".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 959;

        wordle.ApplyGuess("atman".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 339;

        wordle.ApplyGuess("caird".toCharArray(), new byte[]{0,0,1,1,0});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("titer".toCharArray(), new byte[]{2,1,0,1,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest50(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("hetes".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2308;

        wordle.ApplyGuess("klett".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 1341;

        wordle.ApplyGuess("weens".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 766;

        wordle.ApplyGuess("amias".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 114;

        wordle.ApplyGuess("wocks".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 12;

        wordle.ApplyGuess("gogga".toCharArray(), new byte[]{0,2,0,0,2});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("poppa".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest51(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("apery".toCharArray(), new byte[]{1,0,1,1,0});
        assert wordle.getAnswers().size() == 301;

        wordle.ApplyGuess("prees".toCharArray(), new byte[]{0,1,0,2,2});
        assert wordle.getAnswers().size() == 23;

        wordle.ApplyGuess("tares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 12;

        wordle.ApplyGuess("fares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 11;

        wordle.ApplyGuess("lares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 10;

        wordle.ApplyGuess("wares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 9;

        wordle.ApplyGuess("vares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("dares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("hares".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("nares".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest52(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("eaned".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 1161;

        wordle.ApplyGuess("mucky".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 59;

        wordle.ApplyGuess("fezzy".toCharArray(), new byte[]{0,2,0,0,2});
        assert wordle.getAnswers().size() == 34;

        wordle.ApplyGuess("seity".toCharArray(), new byte[]{0,2,0,1,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("terry".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest53(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("toric".toCharArray(), new byte[]{0,1,1,1,0});
        assert wordle.getAnswers().size() == 32;

        wordle.ApplyGuess("oriel".toCharArray(), new byte[]{1,1,1,0,0});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("rioja".toCharArray(), new byte[]{1,2,1,0,0});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("fibro".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest54(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("since".toCharArray(), new byte[]{0,2,1,0,0});
        assert wordle.getAnswers().size() == 52;

        wordle.ApplyGuess("lipin".toCharArray(), new byte[]{0,2,0,2,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest55(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("kithe".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 2031;

        wordle.ApplyGuess("deshi".toCharArray(), new byte[]{2,2,1,0,0});
        assert wordle.getAnswers().size() == 31;

        wordle.ApplyGuess("deers".toCharArray(), new byte[]{2,2,1,0,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("dexes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("debes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("deles".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("denes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest56(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("bowel".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 822;

        wordle.ApplyGuess("kendo".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 402;

        wordle.ApplyGuess("sabed".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 50;

        wordle.ApplyGuess("gogga".toCharArray(), new byte[]{0,2,0,0,1});
        assert wordle.getAnswers().size() == 21;

        wordle.ApplyGuess("coach".toCharArray(), new byte[]{0,2,2,0,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("foamy".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest57(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("aygre".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 1620;

        wordle.ApplyGuess("adzed".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 1349;

        wordle.ApplyGuess("dowle".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 107;

        wordle.ApplyGuess("swaps".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 44;

        wordle.ApplyGuess("oakum".toCharArray(), new byte[]{1,2,0,0,1});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("macon".toCharArray(), new byte[]{2,2,0,1,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest58(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("lulus".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 819;

        wordle.ApplyGuess("ryots".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 58;

        wordle.ApplyGuess("thale".toCharArray(), new byte[]{1,0,1,1,0});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("fatal".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest59(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("vodun".toCharArray(), new byte[]{0,0,0,1,2});
        assert wordle.getAnswers().size() == 44;

        wordle.ApplyGuess("upran".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 9;

        wordle.ApplyGuess("cutin".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest60(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("amici".toCharArray(), new byte[]{2,0,0,0,0});
        assert wordle.getAnswers().size() == 407;

        wordle.ApplyGuess("fouer".toCharArray(), new byte[]{0,0,0,2,1});
        assert wordle.getAnswers().size() == 15;

        wordle.ApplyGuess("adred".toCharArray(), new byte[]{2,0,2,2,0});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("ayres".toCharArray(), new byte[]{2,0,2,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("arret".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest61(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("murks".toCharArray(), new byte[]{0,0,2,2,2});
        assert wordle.getAnswers().size() == 35;

        wordle.ApplyGuess("nerks".toCharArray(), new byte[]{0,0,2,2,2});
        assert wordle.getAnswers().size() == 26;

        wordle.ApplyGuess("works".toCharArray(), new byte[]{0,0,2,2,2});
        assert wordle.getAnswers().size() == 17;

        wordle.ApplyGuess("larks".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest62(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("chams".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 33;

        wordle.ApplyGuess("rehem".toCharArray(), new byte[]{1,0,1,2,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest63(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("smogs".toCharArray(), new byte[]{0,0,2,0,0});
        assert wordle.getAnswers().size() == 392;

        wordle.ApplyGuess("ziffs".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 275;

        wordle.ApplyGuess("crocs".toCharArray(), new byte[]{0,0,2,0,0});
        assert wordle.getAnswers().size() == 117;

        wordle.ApplyGuess("danny".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("exode".toCharArray(), new byte[]{1,0,2,1,0});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("wooed".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("pooed".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("booed".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest64(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("toffs".toCharArray(), new byte[]{2,2,0,0,0});
        assert wordle.getAnswers().size() == 76;

        wordle.ApplyGuess("today".toCharArray(), new byte[]{2,2,0,0,0});
        assert wordle.getAnswers().size() == 34;

        wordle.ApplyGuess("toric".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("toxic".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("tonic".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest65(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("roved".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 219;

        wordle.ApplyGuess("kirks".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 110;

        wordle.ApplyGuess("taupe".toCharArray(), new byte[]{1,0,0,1,1});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("petto".toCharArray(), new byte[]{1,2,2,0,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest66(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("pious".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 1885;

        wordle.ApplyGuess("brawn".toCharArray(), new byte[]{2,1,1,0,0});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("baler".toCharArray(), new byte[]{2,2,0,0,1});
        assert wordle.getAnswers().size() == 9;

        wordle.ApplyGuess("bajra".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("bakra".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest67(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("smarm".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 1345;

        wordle.ApplyGuess("sizer".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 584;

        wordle.ApplyGuess("buggy".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 196;

        wordle.ApplyGuess("sheva".toCharArray(), new byte[]{0,1,0,0,1});
        assert wordle.getAnswers().size() == 34;

        wordle.ApplyGuess("halal".toCharArray(), new byte[]{1,0,1,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("lotah".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest68(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("vitta".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 598;

        wordle.ApplyGuess("ziffs".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 11;

        wordle.ApplyGuess("fluyt".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest69(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("laths".toCharArray(), new byte[]{0,0,1,0,1});
        assert wordle.getAnswers().size() == 271;

        wordle.ApplyGuess("wakfs".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 216;

        wordle.ApplyGuess("rumbo".toCharArray(), new byte[]{0,2,1,0,0});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("muist".toCharArray(), new byte[]{2,2,1,1,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest70(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("retox".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 1158;

        wordle.ApplyGuess("pitot".toCharArray(), new byte[]{2,0,0,1,0});
        assert wordle.getAnswers().size() == 69;

        wordle.ApplyGuess("psoas".toCharArray(), new byte[]{2,1,1,0,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("popsy".toCharArray(), new byte[]{2,2,0,1,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest71(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("newer".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 1119;

        wordle.ApplyGuess("tyees".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 99;

        wordle.ApplyGuess("dinky".toCharArray(), new byte[]{0,0,2,0,2});
        assert wordle.getAnswers().size() == 18;

        wordle.ApplyGuess("gunny".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest72(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("exist".toCharArray(), new byte[]{1,0,0,2,0});
        assert wordle.getAnswers().size() == 141;

        wordle.ApplyGuess("raffs".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("cress".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest73(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("stilb".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 736;

        wordle.ApplyGuess("psych".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 372;

        wordle.ApplyGuess("speal".toCharArray(), new byte[]{0,0,1,1,1});
        assert wordle.getAnswers().size() == 53;

        wordle.ApplyGuess("daled".toCharArray(), new byte[]{0,1,1,1,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest74(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("trugs".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 1051;

        wordle.ApplyGuess("terai".toCharArray(), new byte[]{0,0,2,2,0});
        assert wordle.getAnswers().size() == 32;

        wordle.ApplyGuess("joram".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("coram".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest75(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("aumil".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 1227;

        wordle.ApplyGuess("wider".toCharArray(), new byte[]{0,1,0,0,1});
        assert wordle.getAnswers().size() == 94;

        wordle.ApplyGuess("trios".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("fribs".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("crips".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest76(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("raise".toCharArray(), new byte[]{1,0,0,1,0});
        assert wordle.getAnswers().size() == 233;

        wordle.ApplyGuess("cruve".toCharArray(), new byte[]{0,1,1,0,0});
        assert wordle.getAnswers().size() == 59;

        wordle.ApplyGuess("surly".toCharArray(), new byte[]{2,2,1,0,0});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("sutor".toCharArray(), new byte[]{2,2,0,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest77(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("exies".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 489;

        wordle.ApplyGuess("honky".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 24;

        wordle.ApplyGuess("jehus".toCharArray(), new byte[]{0,1,1,0,2});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("shews".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("chefs".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("bhels".toCharArray(), new byte[]{0,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest78(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("chyle".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2990;

        wordle.ApplyGuess("kaneh".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 387;

        wordle.ApplyGuess("kayak".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 285;

        wordle.ApplyGuess("vilde".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 140;

        wordle.ApplyGuess("pipes".toCharArray(), new byte[]{1,0,0,0,2});
        assert wordle.getAnswers().size() == 15;

        wordle.ApplyGuess("gamps".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("ramps".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("tamps".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest79(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("stylo".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 1913;

        wordle.ApplyGuess("jingo".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("hejab".toCharArray(), new byte[]{0,0,2,1,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest80(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("ridic".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 692;

        wordle.ApplyGuess("rooms".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 124;

        wordle.ApplyGuess("cigar".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 68;

        wordle.ApplyGuess("spifs".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest81(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("jatos".toCharArray(), new byte[]{0,1,0,0,2});
        assert wordle.getAnswers().size() == 469;

        wordle.ApplyGuess("reest".toCharArray(), new byte[]{2,2,0,1,0});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("reaks".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest82(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("caber".toCharArray(), new byte[]{0,1,0,1,1});
        assert wordle.getAnswers().size() == 202;

        wordle.ApplyGuess("pylon".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 114;

        wordle.ApplyGuess("royal".toCharArray(), new byte[]{1,0,0,1,0});
        assert wordle.getAnswers().size() == 70;

        wordle.ApplyGuess("irate".toCharArray(), new byte[]{0,1,2,1,1});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("heart".toCharArray(), new byte[]{0,2,2,2,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest83(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("curia".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 661;

        wordle.ApplyGuess("vrouw".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 143;

        wordle.ApplyGuess("omers".toCharArray(), new byte[]{0,0,1,1,2});
        assert wordle.getAnswers().size() == 12;

        wordle.ApplyGuess("reses".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("rekes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("reges".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("redes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("rezes".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest84(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("horme".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 1666;

        wordle.ApplyGuess("vaned".toCharArray(), new byte[]{0,0,0,2,0});
        assert wordle.getAnswers().size() == 248;

        wordle.ApplyGuess("clipe".toCharArray(), new byte[]{0,1,1,0,1});
        assert wordle.getAnswers().size() == 19;

        wordle.ApplyGuess("gibel".toCharArray(), new byte[]{0,2,0,2,1});
        assert wordle.getAnswers().size() == 10;

        wordle.ApplyGuess("lites".toCharArray(), new byte[]{1,2,1,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest85(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("feens".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 694;

        wordle.ApplyGuess("kaphs".toCharArray(), new byte[]{1,0,0,0,0});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("dinky".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest86(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("solan".toCharArray(), new byte[]{0,0,0,1,1});
        assert wordle.getAnswers().size() == 339;

        wordle.ApplyGuess("shirt".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 44;

        wordle.ApplyGuess("anker".toCharArray(), new byte[]{1,1,0,1,1});
        assert wordle.getAnswers().size() == 10;

        wordle.ApplyGuess("range".toCharArray(), new byte[]{1,1,1,0,1});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("frena".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("urena".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest87(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("croze".toCharArray(), new byte[]{2,1,1,0,0});
        assert wordle.getAnswers().size() == 35;

        wordle.ApplyGuess("coral".toCharArray(), new byte[]{2,1,1,0,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest88(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("lyric".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 2927;

        wordle.ApplyGuess("kanzu".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 285;

        wordle.ApplyGuess("riven".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 152;

        wordle.ApplyGuess("spelt".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 14;

        wordle.ApplyGuess("dubbo".toCharArray(), new byte[]{0,2,1,0,1});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest89(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("tucks".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 3123;

        wordle.ApplyGuess("choil".toCharArray(), new byte[]{0,0,1,1,1});
        assert wordle.getAnswers().size() == 22;

        wordle.ApplyGuess("logoi".toCharArray(), new byte[]{1,1,0,0,1});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("oiled".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest90(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("cajon".toCharArray(), new byte[]{2,2,0,0,0});
        assert wordle.getAnswers().size() == 122;

        wordle.ApplyGuess("yelps".toCharArray(), new byte[]{0,0,2,0,2});
        assert wordle.getAnswers().size() == 4;

        wordle.ApplyGuess("calks".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("calms".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("calls".toCharArray(), new byte[]{2,2,2,0,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest91(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("clime".toCharArray(), new byte[]{0,0,1,1,0});
        assert wordle.getAnswers().size() == 171;

        wordle.ApplyGuess("gaped".toCharArray(), new byte[]{0,1,0,0,0});
        assert wordle.getAnswers().size() == 34;

        wordle.ApplyGuess("miaou".toCharArray(), new byte[]{1,1,1,0,0});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("amrit".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest92(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("lease".toCharArray(), new byte[]{0,1,1,0,0});
        assert wordle.getAnswers().size() == 367;

        wordle.ApplyGuess("toros".toCharArray(), new byte[]{2,0,0,0,0});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("tamed".toCharArray(), new byte[]{2,1,1,1,0});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest93(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("micra".toCharArray(), new byte[]{0,1,0,1,0});
        assert wordle.getAnswers().size() == 277;

        wordle.ApplyGuess("knaps".toCharArray(), new byte[]{0,0,0,1,0});
        assert wordle.getAnswers().size() == 13;

        wordle.ApplyGuess("privy".toCharArray(), new byte[]{2,2,2,0,0});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("pried".toCharArray(), new byte[]{2,2,2,2,0});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("prier".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest94(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("taxon".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 1250;

        wordle.ApplyGuess("posts".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 345;

        wordle.ApplyGuess("wolve".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 32;

        wordle.ApplyGuess("hails".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 8;

        wordle.ApplyGuess("cauls".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 5;

        wordle.ApplyGuess("daals".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("jarls".toCharArray(), new byte[]{0,2,2,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("marls".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest95(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("mazes".toCharArray(), new byte[]{0,0,0,2,1});
        assert wordle.getAnswers().size() == 187;

        wordle.ApplyGuess("plant".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 82;

        wordle.ApplyGuess("shrew".toCharArray(), new byte[]{2,0,1,2,0});
        assert wordle.getAnswers().size() == 16;

        wordle.ApplyGuess("seder".toCharArray(), new byte[]{2,0,0,2,2});
        assert wordle.getAnswers().size() == 10;

        wordle.ApplyGuess("sober".toCharArray(), new byte[]{2,0,0,2,2});
        assert wordle.getAnswers().size() == 7;

        wordle.ApplyGuess("skier".toCharArray(), new byte[]{2,0,1,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("sixer".toCharArray(), new byte[]{2,2,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest96(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("marts".toCharArray(), new byte[]{0,1,0,0,2});
        assert wordle.getAnswers().size() == 359;

        wordle.ApplyGuess("chant".toCharArray(), new byte[]{0,0,1,0,0});
        assert wordle.getAnswers().size() == 118;

        wordle.ApplyGuess("bawrs".toCharArray(), new byte[]{0,1,0,0,2});
        assert wordle.getAnswers().size() == 96;

        wordle.ApplyGuess("divas".toCharArray(), new byte[]{0,0,0,1,2});
        assert wordle.getAnswers().size() == 14;

        wordle.ApplyGuess("aulos".toCharArray(), new byte[]{2,0,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("apsos".toCharArray(), new byte[]{2,0,1,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest97(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("quoad".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 645;

        wordle.ApplyGuess("tally".toCharArray(), new byte[]{0,0,0,2,0});
        assert wordle.getAnswers().size() == 20;

        wordle.ApplyGuess("gusle".toCharArray(), new byte[]{0,2,1,2,0});
        assert wordle.getAnswers().size() == 9;

        wordle.ApplyGuess("nurls".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 2;

        wordle.ApplyGuess("buhls".toCharArray(), new byte[]{0,2,0,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest98(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("roons".toCharArray(), new byte[]{2,1,0,0,1});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("resow".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest99(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("rumba".toCharArray(), new byte[]{0,2,0,0,0});
        assert wordle.getAnswers().size() == 468;

        wordle.ApplyGuess("ariot".toCharArray(), new byte[]{0,0,0,0,1});
        assert wordle.getAnswers().size() == 67;

        wordle.ApplyGuess("tuple".toCharArray(), new byte[]{1,2,0,0,1});
        assert wordle.getAnswers().size() == 6;

        wordle.ApplyGuess("cutes".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;

    }
    private static void PythonTest100(){
        WordleGuesser wordle = new WordleGuesser(Main.GetWords());
        assert wordle.getAnswers().size() == 12972;

        wordle.ApplyGuess("crews".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 1452;

        wordle.ApplyGuess("cried".toCharArray(), new byte[]{0,0,0,0,0});
        assert wordle.getAnswers().size() == 864;

        wordle.ApplyGuess("quats".toCharArray(), new byte[]{0,0,1,0,2});
        assert wordle.getAnswers().size() == 162;

        wordle.ApplyGuess("yirrs".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 145;

        wordle.ApplyGuess("buiks".toCharArray(), new byte[]{0,0,0,0,2});
        assert wordle.getAnswers().size() == 96;

        wordle.ApplyGuess("molas".toCharArray(), new byte[]{1,0,0,2,2});
        assert wordle.getAnswers().size() == 3;

        wordle.ApplyGuess("samas".toCharArray(), new byte[]{2,2,2,2,2});
        assert wordle.getAnswers().size() == 1;
    }
}
